-- Hourly crowd forecast profiles generated by model/hourly-gradient-v1.
-- Live readings remain upstream; this table stores only compact historical profiles.
create table if not exists public.crowd_hourly_profiles (
  location_id bigint not null references public.pedestrian_sensors (location_id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  season text not null check (season in ('summer', 'autumn', 'winter', 'spring')),
  hour_of_day smallint not null check (hour_of_day between 0 and 23),
  baseline_ppm double precision not null check (baseline_ppm >= 0),
  trimmed_mean_ppm double precision not null check (trimmed_mean_ppm >= 0),
  p25_ppm double precision not null check (p25_ppm >= 0),
  p75_ppm double precision not null check (p75_ppm >= 0),
  gradient_ppm_per_hour double precision not null,
  sample_count integer not null check (sample_count >= 0),
  quality_flag text not null check (quality_flag in ('ok', 'low_sample', 'fallback')),
  source_start_date date not null,
  source_end_date date not null,
  model_version text not null,
  imported_at timestamptz not null default timezone('utc', now()),
  primary key (location_id, day_of_week, season, hour_of_day, model_version)
);

create index if not exists crowd_hourly_profiles_lookup_idx
  on public.crowd_hourly_profiles (model_version, day_of_week, season, hour_of_day);

comment on table public.crowd_hourly_profiles is
  'Compact hourly pedestrian forecast profiles. Values are persons per minute and are served through the Express API.';

alter table public.crowd_hourly_profiles enable row level security;

revoke all on table public.crowd_hourly_profiles from anon, authenticated;
grant select, insert, update, delete on table public.crowd_hourly_profiles to service_role;

-- These historical sensors are no longer part of the current map catalogue.
delete from public.crowd_hourly_profiles where location_id in (28, 65, 78);
